#apiVersion: v1
#kind: Namespace
#metadata:
#    name: vsp-blockchain

# I think we dont need this, as the namespace is already created

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: minimal-node
    namespace: vsp-blockchain
spec:
    replicas: 1
    selector:
        matchLabels:
            app: minimal-node
    template:
        metadata:
            labels:
                app: minimal-node
        spec:
            containers:
                - name: node
                  image: ghcr.io/bjoern621/vsp-blockchain-miner:latest
                  imagePullPolicy: Always
                  env:
                      - name: APP_PORT
                        value: "50050"
                      - name: P2P_PORT
                        value: "50051"
                      - name: APP_LISTEN_ADDR
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: P2P_LISTEN_ADDR
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: ADDITIONAL_SERVICES
                        value: "app"
                  ports:
                      - name: app
                        containerPort: 50050
                        protocol: TCP
                      - name: p2p
                        containerPort: 50051
                        protocol: TCP
                  resources:
                      requests:
                          cpu: "100m"
                          memory: "128Mi"
                      limits:
                          cpu: "500m"
                          memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
    name: minimal-node
    namespace: vsp-blockchain
spec:
    selector:
        app: minimal-node
    ports:
        - name: app
          port: 50050
          targetPort: 50050

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: miner
    namespace: vsp-blockchain
spec:
    serviceName: miner-headless
    replicas: 3
    selector:
        matchLabels:
            app: miner
    template:
        metadata:
            labels:
                app: miner
        spec:
            containers:
                - name: miner
                  image: ghcr.io/bjoern621/vsp-blockchain-miner:latest
                  imagePullPolicy: Always
                  env:
                      - name: APP_PORT
                        value: "50050"
                      - name: P2P_PORT
                        value: "50051"
                      - name: APP_LISTEN_ADDR
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: P2P_LISTEN_ADDR
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: ADDITIONAL_SERVICES
                        value: "miner, blockchain_full, app"
                  ports:
                      - name: app
                        containerPort: 50050
                        protocol: TCP
                      - name: p2p
                        containerPort: 50051
                        protocol: TCP
                  resources:
                      requests:
                          cpu: "100m"
                          memory: "128Mi"
                      limits:
                          cpu: "500m"
                          memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
    name: miner-headless
    namespace: vsp-blockchain
spec:
    clusterIP: None
    selector:
        app: miner
    ports:
        - name: p2p
          port: 50051
          targetPort: 50051

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: spv
    namespace: vsp-blockchain
spec:
    replicas: 1
    selector:
        matchLabels:
            app: spv
    template:
        metadata:
            labels:
                app: spv
        spec:
            containers:
                - name: spv
                  image: ghcr.io/bjoern621/vsp-blockchain-miner:latest
                  imagePullPolicy: Always
                  env:
                      - name: APP_PORT
                        value: "50050"
                      - name: P2P_PORT
                        value: "50051"
                      - name: APP_LISTEN_ADDR
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: P2P_LISTEN_ADDR
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: ADDITIONAL_SERVICES
                        value: "wallet, blockchain_simple, app"
                  ports:
                      - name: app
                        containerPort: 50050
                        protocol: TCP
                      - name: p2p
                        containerPort: 50051
                        protocol: TCP
                  resources:
                      requests:
                          cpu: "100m"
                          memory: "128Mi"
                      limits:
                          cpu: "500m"
                          memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
    name: spv-service
    namespace: vsp-blockchain
spec:
    selector:
        app: spv
    ports:
        - name: grpc
          port: 50051
          targetPort: 50051

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: rest-api
    namespace: vsp-blockchain
spec:
    replicas: 1
    selector:
        matchLabels:
            app: rest-api
    template:
        metadata:
            labels:
                app: rest-api
        spec:
            containers:
                - name: rest-api
                  image: ghcr.io/bjoern621/vsp-blockchain-rest-api:latest
                  imagePullPolicy: Always
                  env:
                      - name: APP_GRPC_ADDR_PORT
                        value: "spv-service:50050"
                  ports:
                      - containerPort: 8080
                  resources:
                      requests:
                          cpu: "100m"
                          memory: "128Mi"
                      limits:
                          cpu: "500m"
                          memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
    name: rest-api-service
    namespace: vsp-blockchain
spec:
    type: LoadBalancer
    selector:
        app: rest-api
    ports:
        - port: 8080
          targetPort: 8080
