openapi: 3.0.3
info:
  title: V$-GOIN API
  version: 1.0.0
tags:
  - name: Payment
    description: Everything about the Payment
  - name: KeyTools
    description: Tools for creating and managing Keys.

paths:
  /transaction:
    post:
      summary: Executes a transaction
      description: Transfers the given amount from the sender to the recipient as long as sender can provide the amount and the private key can create a valid signature
      tags:
        - Payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - recipientPublicKeyHASH
                - amount
                - senderPrivateKey
              properties:
                recipientPublicKeyHASH:
                  type: string
                  example: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
                  description: Base64-encoded public key hash of the recipient.
                amount:
                  type: integer
                  minimum: 1
                  example: 100
                  description: The amount of V$-Goin the sender wants to transfer
                senderPrivateKey:
                  type: string
                  example: dGhpcyBpcyBhIHNpZ25hdHVyZSBleGFtcGxlLg==
                  description: The private key belonging to the public key of the sender
      responses:
        '200':
          description: Transaction successfully executed
        '400':
          description: Insufficient funds for the given transaction
        '401':
          description: Invalid private key
  /balance:
    get:
      summary: Returns the balance tied to the given public key hash
      tags:
        - Payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - keyHash
              properties:
                keyHash:
                  type: string
                  example: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
                  description: Base64-encoded public key hash whose balance is requested.
      responses:
        '200':
          description: Successful response with current balance.
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: integer
                    example: 1250
                    description: The balance tied to the given key hash.
        '400':
          description: No balance tied to the given key
  /history:
    get:
      summary: Returns the history of transactions involving the given Key hash
      tags:
        - Payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - keyHash
              properties:
                keyHash:
                  type: string
                  example: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
                  description: Base64-encoded public key hash whose history is requested.
      responses:
        '200':
          description: Successful response with keys history.
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactions:
                    type: array
                    items:
                      type: string
                    example: [ "A sent B 100", "B sent A 50", "A sent C 10"]
        '400':
          description: Key hash was not involved in any transactions

  /address:
    get:
      summary: Returns the V$Address to a corresponding private key.
      tags:
        - KeyTools
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              description: The private key
              example: "The private key"
      responses:
        '200':
          description: Successful response with V$Address and the private key.
          content:
            application/json:
              schema:
                type: string
                description: The V$Address
                example: "The V$Address"
        '400':
          description: private Key is not Valid

  /address/new:
    get:
      summary: Returns a new V$Address with the corresponding private key.
      tags:
        - KeyTools
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: string
              description: "Seed for private Key generation"
              example: "Seed for private Key generation"
      responses:
        '200':
          description: Successful response with V$Address and the private key.
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
                    description: The new V$Address.
                  privateKey:
                    type: string
                    description: The new private key.
                required:
                  - address
                  - privateKey




